name: 'PR Automator'
on:
  issues:
    types:
      - opened
  pull_request:
    types:
      - opened
      - edited
      - converted_to_draft
      - ready_for_review

jobs:
  Validate:
    runs-on: ubuntu-latest
    steps:
      - uses: 10up/action-pr-automator@fix/pr-validation
        with:
          fail-label: needs:feedback
          pass-label: needs:code-review
          reviewers: |
            iamdharmesh
            faisal-alvi
            wpghactionbot
          issue-comment: Hi {author}, Thank you for opening this issue. We will look into it and get back to you soon.
          pr-comment: Hi {author}, Thank you for opening this PR. We will look into it and get back to you soon.
          comment-ignore-users: |
            iamdharmesh
          validate-changelog: false
          validate-credits: false
          validate-description: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
