name: Props Bot

on:
  # Gathers all participants for pull requests to assist in giving proper credit.
  pull_request:
  issue_comment:
    types: [created, edited, deleted]
  pull_request_review:
  pull_request_review_comment:

# Cancels all previous workflow runs for pull requests that have not completed.
concurrency:
  # The concurrency group contains the workflow name and the branch name for pull requests
  # or the commit hash for any other events.
  group: ${{ github.workflow }}-${{ github.event_name == 'pull_request' && github.head_ref || github.sha }}
  cancel-in-progress: true

jobs:
  pull_request_participants:
    name: Collect props
    runs-on: ubuntu-latest
    timeout-minutes: 20

    # Collects a list of contributors for a pull request and shares a list of
    # Co-authored-by: trailers for merging contributors.
    steps:
      - name: Compile contributor list
        uses: iamdharmesh/wordpress-props@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

